/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ajinkyabhushan
 */
public class ClubMembership extends javax.swing.JFrame {
    
    ButtonGroup groupGender = new ButtonGroup();
    
    CSVFile file = new CSVFile();
    List<Member>  arraylistData;
    /**
     * Creates new form ClubMembership
     */
    public ClubMembership() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
        showCustomerList(model);
        groupGender.add(radioMale);
        groupGender.add(radioFemale);
    }
    
    
    //custom functions from my end 
    
    //1st Function
    private String getSelectedRadioValue(ButtonGroup group){
        for(Enumeration<AbstractButton> buttons = group.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()){
                return button.getText();
            }
        }
        return null;
    }
    
    //2nd Fuction
    private void showCustomerList(DefaultTableModel model){
        try {
           
             List<Member> arraylistData = file.readData();
            String rowData[] = new String[arraylistData.size()];
            for (int i = 0; i < arraylistData.size(); i++) {
            rowData[0] = arraylistData.get(i).getMembership_Number();
            rowData[2] = arraylistData.get(i).getFirst_name();
            rowData[1] = arraylistData.get(i).getLast_name();
            rowData[3] = arraylistData.get(i).getDate();
            rowData[4] = arraylistData.get(i).getGender();
            rowData[5] = arraylistData.get(i).getAddress();
            rowData[6] = arraylistData.get(i).getPhone_no();
            rowData[7] = arraylistData.get(i).ageCalculate(rowData[3]); //
            rowData[8] = arraylistData.get(i).getMemberType();
            rowData[9] = arraylistData.get(i).getStartDate();
            rowData[10] = arraylistData.get(i).endDateCalculate(rowData[9], rowData[8]);
            rowData[11] = arraylistData.get(i).feesCalculate(rowData[8]);
            model.addRow(rowData);
            } 
        } catch (IOException ex) {
            Logger.getLogger(ClubMembership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //3rd Function
     void clearFields(){
         textFirstName.setText("");
         textLastName.setText("");
         textareaAddress.setText("");
         textDateOfBirth.setText("");
         textContact.setText("");
         groupGender.clearSelection();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        textSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboFilter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnExportCSV = new javax.swing.JButton();
        panelButton = new javax.swing.JPanel();
        btnAddCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnGrossRevenue = new javax.swing.JButton();
        panelField = new javax.swing.JPanel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelDateOfBirth = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelContactNo = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textDateOfBirth = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaAddress = new javax.swing.JTextArea();
        textContact = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        labelCustomerType = new javax.swing.JLabel();
        comboCustomerType = new javax.swing.JComboBox<>();
        labelStartDate = new javax.swing.JLabel();
        textStartDate = new javax.swing.JTextField();
        btnEditCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panelTable.setBackground(new java.awt.Color(153, 153, 153));
        panelTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Manager v1.0");

        tableCustomer.setAutoCreateRowSorter(true);
        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Date of Birth", "Gender", "Address", "Contact No.", "Age", "Fees", "Start Date", "End Date", "Member Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCustomer);

        textSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Find");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search :");

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "ID", "Name", "Address" }));
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filter :");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExportCSV.setBackground(new java.awt.Color(255, 102, 255));
        btnExportCSV.setText("Export");
        btnExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addComponent(btnExportCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(textSearch)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExportCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelButton.setBackground(new java.awt.Color(51, 51, 51));

        btnAddCustomer.setBackground(new java.awt.Color(255, 255, 102));
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteCustomer.setText("Delete Customer");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        btnGrossRevenue.setBackground(new java.awt.Color(51, 255, 102));
        btnGrossRevenue.setText("Total Stats");
        btnGrossRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrossRevenueActionPerformed(evt);
            }
        });

        panelField.setBackground(new java.awt.Color(51, 51, 51));
        panelField.setForeground(new java.awt.Color(255, 255, 255));

        labelFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(255, 255, 255));
        labelFirstName.setText("First Name");

        labelLastName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(255, 255, 255));
        labelLastName.setText("Last Name");

        labelDateOfBirth.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelDateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        labelDateOfBirth.setText("Date of Birth");

        labelGender.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelGender.setForeground(new java.awt.Color(255, 255, 255));
        labelGender.setText("Gender");

        labelAddress.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(255, 255, 255));
        labelAddress.setText("Address");

        labelContactNo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelContactNo.setForeground(new java.awt.Color(255, 255, 255));
        labelContactNo.setText("Contact No.");

        textFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFirstNameActionPerformed(evt);
            }
        });

        textareaAddress.setColumns(20);
        textareaAddress.setRows(5);
        jScrollPane2.setViewportView(textareaAddress);

        radioMale.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        radioMale.setForeground(new java.awt.Color(255, 255, 255));
        radioMale.setText("Male");

        radioFemale.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        radioFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioFemale.setText("Female");

        labelCustomerType.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelCustomerType.setForeground(new java.awt.Color(255, 255, 255));
        labelCustomerType.setText("Customer Type");

        comboCustomerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Monthly", "Single Yearly", "Family Monthly", "Family Yearly", "Vistor" }));
        comboCustomerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCustomerTypeActionPerformed(evt);
            }
        });

        labelStartDate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelStartDate.setForeground(new java.awt.Color(255, 255, 255));
        labelStartDate.setText("Start Date");

        javax.swing.GroupLayout panelFieldLayout = new javax.swing.GroupLayout(panelField);
        panelField.setLayout(panelFieldLayout);
        panelFieldLayout.setHorizontalGroup(
            panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFieldLayout.createSequentialGroup()
                        .addComponent(labelCustomerType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboCustomerType, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFieldLayout.createSequentialGroup()
                        .addComponent(labelFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFieldLayout.createSequentialGroup()
                        .addComponent(labelLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFieldLayout.createSequentialGroup()
                        .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDateOfBirth)
                            .addComponent(labelGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFieldLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(radioMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioFemale))
                            .addComponent(textDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFieldLayout.createSequentialGroup()
                        .addComponent(labelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFieldLayout.createSequentialGroup()
                        .addComponent(labelContactNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textContact, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFieldLayout.createSequentialGroup()
                        .addComponent(labelStartDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFieldLayout.setVerticalGroup(
            panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFieldLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustomerType)
                    .addComponent(comboCustomerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDateOfBirth)
                    .addComponent(textDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMale)
                    .addComponent(radioFemale)
                    .addComponent(labelGender))
                .addGap(18, 18, 18)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddress)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContactNo)
                    .addComponent(textContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStartDate)
                    .addComponent(textStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEditCustomer.setBackground(new java.awt.Color(51, 102, 255));
        btnEditCustomer.setText("Edit Customer");
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrossRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrossRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFilterActionPerformed

    private void textSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        if(!(textFirstName.getText().isEmpty() && textLastName.getText().isEmpty() && textDateOfBirth.getText().isEmpty())){       //Validation
            
            DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
            Member member = new Member();
            Visitor visitor = new Visitor();
            if (comboCustomerType.getSelectedItem().toString() == "Vistor"){
                file.writeList(visitor.toString());
            }
            //System.out.println(getSelectedRadioValue(groupGender));
            member.Member(textFirstName.getText(), textLastName.getText(), textDateOfBirth.getText(), getSelectedRadioValue(groupGender), textareaAddress.getText(), textContact.getText(),textStartDate.getText(), comboCustomerType.getSelectedItem().toString());
            file.writeList(member.printAll());
            String rowData[] = new String[12];
            rowData[0] = member.getMembership_Number();
            rowData[2] = member.getFirst_name();
            rowData[1] = member.getLast_name();
            rowData[3] = member.getDate();
            rowData[4] = member.getGender();
            rowData[5] = member.getAddress();
            rowData[6] = member.getPhone_no();
            rowData[7] = member.getAge();
            rowData[8] = member.feesCalculate(member.getMemberType());
            rowData[9] = member.getStartDate();
            rowData[11] = member.getMemberType();
            rowData[10] = member.endDateCalculate(rowData[9],rowData[11]);
            //System.out.println(rowData[7]);
            model.addRow(rowData);
            clearFields();
            model.fireTableDataChanged();
        }
        else{
            JOptionPane.showMessageDialog(new JFrame(),"Fields are still empty","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnGrossRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrossRevenueActionPerformed
        // TODO add your handling code here:
        new Stats().setVisible(true);
    }//GEN-LAST:event_btnGrossRevenueActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
       DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
       int selectedrow = tableCustomer.getSelectedRow();
       model.removeRow(selectedrow);
        try {
            // TODO add your handling code here:
            arraylistData = file.readData();
        } catch (IOException ex) {
            Logger.getLogger(ClubMembership.class.getName()).log(Level.SEVERE, null, ex);
        }
          for(int i = 0; i < arraylistData.size(); i++){
            if(textFirstName.getText().equals(arraylistData.get(i).getLast_name())){
                  arraylistData.remove(i);
                  file.removeList(arraylistData);
            }
        }
          model.fireTableDataChanged();
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void textFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameActionPerformed

    private void comboCustomerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCustomerTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCustomerTypeActionPerformed

    private void tableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
        int selectedrowindex = tableCustomer.getSelectedRow();
        textFirstName.setText(model.getValueAt(selectedrowindex, 1).toString());
        textLastName.setText(model.getValueAt(selectedrowindex, 2).toString());
        textDateOfBirth.setText(model.getValueAt(selectedrowindex, 3).toString());
        textareaAddress.setText(model.getValueAt(selectedrowindex, 5).toString());
        if("Male".equals(model.getValueAt(selectedrowindex, 4).toString()) || "male".equals(model.getValueAt(selectedrowindex, 4).toString())){
            radioMale.setSelected(true);
        }else{
            radioFemale.setSelected(true);
        }
    }//GEN-LAST:event_tableCustomerMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
            
            TableRowSorter sorter = new TableRowSorter(model);
            tableCustomer.setRowSorter(sorter);
            sorter.setRowFilter(RowFilter.regexFilter(textSearch.getText().trim()));

    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
            
            TableRowSorter sorter = new TableRowSorter(model);
            tableCustomer.setRowSorter(sorter);
            sorter.setRowFilter(RowFilter.regexFilter(""));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
         Member m = new Member();         
         m.setFirst_name(textFirstName.getText());
         m.setLast_name(textLastName.getText());
         m.setDate(textDateOfBirth.getText());
         m.setGender(groupGender.getSelection().getActionCommand());
         m.setAddress(textareaAddress.getText());
         m.setStartDate(textStartDate.getText());
            model.setValueAt(m.getFirst_name(), tableCustomer.getSelectedRow(), 1);
            model.setValueAt(m.getLast_name(), tableCustomer.getSelectedRow(), 2);
            model.setValueAt(m.getDate(), tableCustomer.getSelectedRow(), 3);
            model.setValueAt(m.getGender(), tableCustomer.getSelectedRow(), 4);
            model.setValueAt(m.getAddress(), tableCustomer.getSelectedRow(), 5);
            model.setValueAt(m.getStartDate(), tableCustomer.getSelectedRow(), 9);   
    }//GEN-LAST:event_btnEditCustomerActionPerformed

    private void btnExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCSVActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        JFileChooser chooser = new JFileChooser();
        DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
        
        chooser.setDialogTitle("Save the file to");
        int save = chooser.showSaveDialog(frame);
        
        if(save == JFileChooser.APPROVE_OPTION){
            try{
                FileWriter filewrite = new FileWriter(new File(chooser.getSelectedFile()+".csv"));
                for(int i = 0; i < model.getRowCount(); i++){
                    for (int j = 0 ; j< model.getColumnCount(); j++){
                        filewrite.write(model.getValueAt(i, j).toString()+", ");
                    }
                    filewrite.write('\n');
                }
            } catch (IOException ex) {
                Logger.getLogger(ClubMembership.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnExportCSVActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClubMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClubMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClubMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClubMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClubMembership().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnExportCSV;
    private javax.swing.JButton btnGrossRevenue;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboCustomerType;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelContactNo;
    private javax.swing.JLabel labelCustomerType;
    private javax.swing.JLabel labelDateOfBirth;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelStartDate;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelField;
    private javax.swing.JPanel panelTable;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField textContact;
    private javax.swing.JTextField textDateOfBirth;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textStartDate;
    private javax.swing.JTextArea textareaAddress;
    // End of variables declaration//GEN-END:variables
}
